### ISSUE TITLE
Issues with BigInt test262-test

### ISSUE THREAD

**Issue by doehyunbaek** [es-meta/esmeta#107]
Currently, two tests involving BigInt is filtered out as such

https://github.com/es-meta/esmeta/blob/7631621384b2a60bc1b4dd3ed8aeb50e1b509eb1/src/main/resources/manuals/default/test262/filtered.json#L312-L313

If you execute these tests, you can confirm both tests failing. There is indeed some issues with these tests.

As I digged down, this was esmeta interpreter malfunctioning because of two reasons.

1. Scala BigDecimal is not a mathematical value.

Ecmascript uses four kinds of numeric values, as mentioned in [the spec](https://tc39.es/ecma262/#sec-mathematical-operations), functions like [BigInt.asIntN](https://tc39.es/ecma262/#sec-bigint.asintn) use this mathematical value to represent certain operations. 

Unfortunately, scala.math.BigDecimal, which esmeta uses to represent mathematical values, do not behave quite the same way in certain situations. 

For example,
```console
scala> scala.math.BigDecimal(2).pow(20) == scala.math.BigInt(2).pow(20)
val res5: Boolean = true
                                                                                                                                                                
scala> scala.math.BigDecimal(2).pow(200) == scala.math.BigInt(2).pow(200)
val res6: Boolean = false
```
It loses equality with BigInt in the latter cases, making it deviate from the desired mathematical property.

This was the reason why test cases involving very big exponent failed, for example

https://github.com/tc39/test262/blob/6c50d46b391efc4847fa1d06718db47cdf3f1723/test/built-ins/BigInt/asIntN/arithmetic.js#L54-L59

2. Scala modulo operation use different modulo operation with respect to ecmascript spec.

When we perform a modulo n, and when one of two is negative, there are two possible definitions of modulo, one giving positive remainder and the other giving negative remainder. For more information, reference [wikipedia article on modulo](https://en.wikipedia.org/wiki/Modulo_operation#In_programming_languages).

Ecmascript uses the [definition returning the positive remainder](https://tc39.es/ecma262/#eqn-modulo), scala uses the [definition returning the negative remainder](https://stackoverflow.com/questions/30003811/in-scala-why-could-remainder-operator-return-a-negative-number).

For example, in scala,
```console
scala> -3 % 4
val res7: Int = -3
```
which spec would have expected 1 as a result.

This was the reason why test cases involving negative dividend failed, for example

https://github.com/tc39/test262/blob/6c50d46b391efc4847fa1d06718db47cdf3f1723/test/built-ins/BigInt/asIntN/arithmetic.js#L33-L35

**Comment by doehyunbaek** [comment]
I opened a PR containing proposed fixes in #108. The adequacy of the fix can be discussed there.

**Comment by jhnaldo** [comment]
Thanks, @doehyunbaek! I fixed this issue using the unlimited math context ([`MathContext.UNLIMITED`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/MathContext.html#UNLIMITED)) as many as possible for [`BigDecimal`](https://scala-lang.org/api/3.1.1/scala/math/BigDecimal.html) in https://github.com/es-meta/esmeta/commit/551249d6401a33dbf377eb65250d14316adcc94f.

**Comment by doehyunbaek** [comment]
testing

Currently, test262 command summarizes yet-to-be supported featurees using error handler defined here.

https://github.com/es-meta/esmeta/blob/189d722a0299ce8481280557e0924e5be75cbd4e/src/main/scala/esmeta/test262/Test262.scala#L79-L84

If we search where Throwable NotSupported is constructed, we can find there are three major kinds.

1. At analyzer(abstract interpretation)

https://github.com/es-meta/esmeta/blob/db29123ef18d8894c9847ed51c2680e04c7e45fb/src/main/scala/esmeta/analyzer/package.scala#L37-L38

2. As EYet,

https://github.com/es-meta/esmeta/blob/7e8eba30a6eab1ddf782134f9cdc8658c2e4c09a/src/main/scala/esmeta/interpreter/Interpreter.scala#L247-L248

3. As YetObj, denoting not yet supported global objects

https://github.com/es-meta/esmeta/blob/87fe33ee835b0ae0d31530eef29eb15cc53a0cee/src/main/scala/esmeta/state/Heap.scala#L19-L26

In addition, there are some two more where it is thrown.

https://github.com/es-meta/esmeta/blob/7e8eba30a6eab1ddf782134f9cdc8658c2e4c09a/src/main/scala/esmeta/interpreter/Interpreter.scala#L668-L669

https://github.com/es-meta/esmeta/blob/7e8eba30a6eab1ddf782134f9cdc8658c2e4c09a/src/main/scala/esmeta/interpreter/Interpreter.scala#L813-L815

Although they are conceptually very different, they are lumped together into `NotSupported(msg: String).

First, we should make them more fine-grained, as other error type does, for example,

https://github.com/es-meta/esmeta/blob/d53ba295d43e402d2ec91bb1ee095222f0f8386c/src/main/scala/esmeta/error/AnalaysisError.scala#L7-L15

`NotSupportedOperation and AnalysisImprecise` are more fine-grained error types of AnalysisError.

I propose to add 3 additional subtypes to `NotSupported`, which are `YetAnalyzer, NotParsable, YetGlobalObject`, naming might, corresponding to three above places. Naming might change in the future.

Then, while performing summary, I intend to classify them into these types, and for YetGlobalObject, further subdivide them according to kinds of these objects.
