### ISSUE TITLE
Rhs only supports a single Condition, but ecmarkup/grammarkdown allow multiple.

### ISSUE THREAD

**Issue by rbuckton** [es-meta/esmeta#133]
In https://tc39.es/proposal-async-explicit-resource-management/#prod-T6VINPU5 I have two rhs constraints: `+Using` and `+Await`. However, `esmeta` complains during the extract phase with an error pointing to the preceding line:

```
========================================
 extract phase
----------------------------------------
[ESMeta v0.1.0] [Parser (List[spec.Production])] [14.110] failure: end of input expected

          [+Using] `using` [no LineTerminator here] [lookahead != `await`] ForBinding[?Yield, ?Await, +Using]
                                                                                                             ^
```

- `grammarkdown`'s `RightHandSide` definition takes a `Constraints`: https://github.com/rbuckton/grammarkdown/blob/main/src/nodes.ts#L1556
- `grammarkdown`'s `Constraints` definition takes multiple `Argument` nodes (i.e., `+Foo`, `~Bar`): https://github.com/rbuckton/grammarkdown/blob/main/src/nodes.ts#L458
- `grammarkdown`'s `EcmarkupEmitter` emits constraints separated by commas:
  - https://github.com/rbuckton/grammarkdown/blob/main/src/emitter/ecmarkup.ts#L145
  - https://github.com/rbuckton/grammarkdown/blob/main/src/emitter/ecmarkup.ts#L337
- `ecmarkup` embeds the text verbatim: https://github.com/tc39/ecmarkup/blob/main/src/RHS.ts#L29
- `esmeta`'s `Rhs` definition only seems to support one `Condition`/`RhsCond`: https://github.com/es-meta/esmeta/blob/main/src/main/scala/esmeta/spec/Rhs.scala#L10

**Comment by doehyunbaek** [comment]
Thanks for the detailed report! I'll take a look.

**Comment by jhnaldo** [comment]
Hi, @rbuckton. Thanks for reporting the issue related to the RHS conditions.

I have a question about the multiple conditions for a single RHS alternative. Is defining multiple conditions the official notation in ECMA-262? The most recent [version](https://tc39.es/ecma262/#sec-grammatical-parameters) only mentions single condition cases, such as `[+Return]` or `[~Return]`.

If so, what is the exact meaning of the multiple conditions for a single RHS alternative? Conjunction or Disjunction? For example, in the following case, is this RHS alternative available when 1) both `Using` and `Await` are true or 2) when one of them is true?
```
[+Using, +Await] using [no LineTerminator here] await [no LineTerminator here] ForBinding[?Yield, +Await, +Using]
```

**Comment by rbuckton** [comment]
I would have to defer to an editor. My expectation is that it is a conjunction, as a disjunction could be represented easily with multiple right-hand sides. The same can't be said for a conjunction. At least, that was my impression when I added the functionality to `grammarkdown`.

**Comment by rbuckton** [comment]
The original feature ask was for a conjunction, and can be found here: https://github.com/rbuckton/grammarkdown/issues/25

**Comment by jhnaldo** [comment]
I supported multiple RHS conditions in #134. I will close this issue if you don't have any other problems related to multiple RHS conditions.

**Comment by rbuckton** [comment]
I've tested this locally and it seems to work fine, thanks!
