### ISSUE TITLE
Create pull request for untyped SDOs

### ISSUE THREAD

**Issue by jhnaldo** [es-meta/esmeta#14]
- `sec-identifiers-runtime-semantics-evaluation`
- `sec-this-keyword-runtime-semantics-evaluation`
- `sec-literals-runtime-semantics-evaluation`
- `sec-array-initializer-runtime-semantics-evaluation`
- `sec-object-initializer-runtime-semantics-evaluation`
- `sec-regular-expression-literals-runtime-semantics-evaluation`
- `sec-template-literals-runtime-semantics-evaluation`
- `sec-grouping-operator-runtime-semantics-evaluation`
- `sec-property-accessors-runtime-semantics-evaluation`
- `sec-new-operator-runtime-semantics-evaluation`
- `sec-function-calls-runtime-semantics-evaluation`
- `sec-super-keyword-runtime-semantics-evaluation`
- `sec-optional-chaining-evaluation`
- `sec-import-call-runtime-semantics-evaluation`
- `sec-tagged-templates-runtime-semantics-evaluation`
- `sec-meta-properties-runtime-semantics-evaluation`
- `sec-postfix-increment-operator-runtime-semantics-evaluation`
- `sec-prefix-increment-operator-runtime-semantics-evaluation`
- `sec-delete-operator-runtime-semantics-evaluation`
- `sec-void-operator-runtime-semantics-evaluation`
- `sec-typeof-operator-runtime-semantics-evaluation`
- `sec-addition-operator-plus-runtime-semantics-evaluation`
- `sec-arrow-function-definitions-runtime-semantics-evaluation`
- `sec-assignment-operators-runtime-semantics-evaluation`
- `sec-async-function-definitions-runtime-semantics-evaluation`
- `sec-asyncgenerator-definitions-evaluation`
- `sec-binary-bitwise-operators-runtime-semantics-evaluation`
- `sec-binary-logical-operators-runtime-semantics-evaluation`
- `sec-bitwise-not-operator-runtime-semantics-evaluation`
- `sec-block-runtime-semantics-evaluation`
- `sec-break-statement-runtime-semantics-evaluation`
- `sec-class-definitions-runtime-semantics-evaluation`
- `sec-comma-operator-runtime-semantics-evaluation`
- `sec-conditional-operator-runtime-semantics-evaluation`
- `sec-continue-statement-runtime-semantics-evaluation`
- `sec-debugger-statement-runtime-semantics-evaluation`
- `sec-empty-statement-runtime-semantics-evaluation`
- `sec-equality-operators-runtime-semantics-evaluation`
- `sec-exp-operator-runtime-semantics-evaluation`
- `sec-exports-runtime-semantics-evaluation`
- `sec-expression-statement-runtime-semantics-evaluation`
- `sec-for-in-and-for-of-statements-runtime-semantics-evaluation`
- `sec-function-definitions-runtime-semantics-evaluation`
- `sec-if-statement-runtime-semantics-evaluation`
- `sec-labelled-statements-runtime-semantics-evaluation`
- `sec-left-shift-operator-runtime-semantics-evaluation`
- `sec-let-and-const-declarations-runtime-semantics-evaluation`
- `sec-logical-not-operator-runtime-semantics-evaluation`
- `sec-module-semantics-runtime-semantics-evaluation`
- `sec-multiplicative-operators-runtime-semantics-evaluation`
- `sec-relational-operators-runtime-semantics-evaluation`
- `sec-return-statement-runtime-semantics-evaluation`
- `sec-script-semantics-runtime-semantics-evaluation`
- `sec-signed-right-shift-operator-runtime-semantics-evaluation`
- `sec-statement-semantics-runtime-semantics-evaluation`
- `sec-subtraction-operator-minus-runtime-semantics-evaluation`
- `sec-switch-statement-runtime-semantics-evaluation`
- `sec-throw-statement-runtime-semantics-evaluation`
- `sec-try-statement-runtime-semantics-evaluation`
- `sec-unary-minus-operator-runtime-semantics-evaluation`
- `sec-unary-plus-operator-runtime-semantics-evaluation`
- `sec-variable-statement-runtime-semantics-evaluation`
- `sec-with-statement-runtime-semantics-evaluation`
- `sec-async-arrow-function-definitions-runtime-semantics-evaluation`
- `sec-generator-function-definitions-runtime-semantics-evaluation`
- `sec-postfix-decrement-operator-runtime-semantics-evaluation`
- `sec-prefix-decrement-operator-runtime-semantics-evaluation`
- `sec-unsigned-right-shift-operator-runtime-semantics-evaluation`
## Wrong cases
- ~`sec-%foriniteratorprototype%.next`~

**Comment by p51lee** [comment]
https://github.com/tc39/ecma262/pull/2619
