### ISSUE TITLE
Support optional terminals

### ISSUE THREAD

**Issue by nicolo-ribaudo** [es-meta/esmeta#144]
Example:
```
NonTerminal : 
  `a` `b`?
```

Terminal symbols can be optional, according to https://tc39.es/ecma262/#sec-optional-symbols.

Ref https://github.com/tc39/ecma262/pull/3057#discussion_r1187363062

**Comment by jhnaldo** [comment]
Hi, @nicolo-ribaudo. Thanks for your issue! I will try to address it as soon as I can.

**Comment by jhnaldo** [comment]
Dear @nicolo-ribaudo, I resolved this issue at https://github.com/es-meta/esmeta/commit/503b2fae9ceb0bbc58162a85d89cad831f29e97c. So, I closed this issue.

**Comment by nicolo-ribaudo** [comment]
Thank you!
