### ISSUE TITLE
esmeta doesn’t support `~~` in grammar

### ISSUE THREAD

**Issue by mathiasbynens** [es-meta/esmeta#145]
See https://github.com/tc39/ecma262/pull/2418#discussion_r1173563802. As part of this patch, we define a grammar that includes `~~`:

```
      <emu-grammar type="definition">
        ClassSetReservedDoublePunctuator :: one of
          `&amp;&amp;` `!!` `##`
          `$$` `%%` `**`
          `++` `,,` `..`
          `::` `;;` `&lt;&lt;`
          `==` `&gt;&gt;` `??`
          `@@` `^^` `&grave;&grave;`
          `~~`
      </emu-grammar>
```

It seems esmeta doesn’t like this for some reason. The check fails: https://github.com/tc39/ecma262/actions/runs/5088350689/jobs/9144652112?pr=2418#step:7:1

```
Run "${ESMETA_HOME}"/bin/esmeta tycheck -status -tycheck:log -tycheck:ignore=esmeta-ignore.json
========================================
 extract phase
----------------------------------------
[ESMeta v0.3.0] [Parser (List[spec.Production])] [2[8](https://github.com/tc39/ecma262/actions/runs/5088350689/jobs/9144652112?pr=2418#step:7:9).[12](https://github.com/tc39/ecma262/actions/runs/5088350689/jobs/9144652112?pr=2418#step:7:13)] failure: end of input expected

          `~~`
           ^
Error: Process completed with exit code 1.
```

@bakkot said:

> No idea what's up with that one; probably an esmeta bug. We'll turn the check off or fix esmeta before merging

It would be great if this could be fixed in esmeta.

**Comment by jhnaldo** [comment]
Hi, @mathiasbynens. Thanks for your kind report on the bugs in the current version of ESMeta.
Since I fixed this issue in https://github.com/es-meta/esmeta/pull/146, I closed this issue.
