### ISSUE TITLE
Unicode terminal parsing does not match grammarkdown

### ISSUE THREAD

**Issue by gibson042** [es-meta/esmeta#147]
[grammarkdown](https://github.com/rbuckton/grammarkdown#character-literals-and-ranges) documents a `U+HHHH` form of expressing terminals which esmeta seems to reject outright, and an underspecified `<…>` form for which esmeta is more restrictive than grammarkdown (cf. https://github.com/rbuckton/grammarkdown/issues/91 , in which I'm hoping to nail down the latter with a more expansive definition matching the actual implementation).

**Comment by jhnaldo** [comment]
This issue is fixed in ESMeta [v0.3.2](https://github.com/es-meta/esmeta/releases/tag/v0.3.2) with the PR #148. So, I close this issue.
