### ISSUE TITLE
`if _x_ is a Y, set _x_ to _z_` should refine the type of _x_

### ISSUE THREAD

**Issue by bakkot** [es-meta/esmeta#149]
[This PR](https://github.com/tc39/ecma262/pull/3066) introduces spec text which looks like this:

```
1. If _fillString_ is *undefined*, set _fillString_ to the String value consisting solely of the code unit 0x0020 (SPACE).
1. Else, set _fillString_ to ? ToString(_fillString_).
1. Return StringPad(_S_, _intMaxLength_, _fillString_, _placement_).
```

That produces an error in esmeta:

```
[ParamTypeMismatch] third parameter _fillString_ of StringPad @ StringPaddingBuiltinsImpl (step 7, 8:23-80)
- expected: String
- actual  : String | Undefined
```

presumably because the first step in my snippet above is not refining the type of `_fillString_` to just `String`. We've added it to esmeta-ignore for now, so there's no urgency, but I wanted to document the issue.

**Comment by jhnaldo** [comment]
I closed this issue since it is resolved in the new type analyzer introduced in [v0.5.0](https://github.com/es-meta/esmeta/releases/tag/v0.5.0).
