### ISSUE TITLE
new notation for Unicode code points in ES grammar

### ISSUE THREAD

**Issue by michaelficarra** [es-meta/esmeta#220]
In https://github.com/tc39/ecma262/pull/3310, we are planning to refer to Unicode code points directly in the grammar using the notation `<U+0000 (NULL)>` (with `<` and `>` encoded as HTML entities `&lt;` and `&gt;` respectively). Currently, esmeta doesn't support parentheses in this position, giving us this error:

![image](https://github.com/es-meta/esmeta/assets/218840/b597dec7-6bd6-4b5b-b67c-84a1460604f5)

**Comment by jhnaldo** [comment]
It is resolved by https://github.com/es-meta/esmeta/pull/222 and merged at https://github.com/tc39/ecma262/pull/3325. So, I close this issue.
