### ISSUE TITLE
esmeta type checker doesn't allow assigning constructors to function objects

### ISSUE THREAD

**Issue by michaelficarra** [es-meta/esmeta#258]
See https://github.com/tc39/ecma262/pull/3287 and the type checker failures at https://github.com/tc39/ecma262/actions/runs/11152432538/job/30998035427?pr=3287.

Constructors are objects with `[[Call]]` and `[[Construct]]` slots. Function objects are objects with `[[Call]]` slots. Therefore, all constructors are function objects. However, esmeta does not allow us to pass constructors to AOs whose parameters have been declared to be function objects.

**Comment by jhnaldo** [comment]
Since we fixed this issue in [v0.4.3](https://github.com/es-meta/esmeta/releases/tag/v0.4.3), we closed this issue. If it is unresolved, please let us know by opening this issue.
