### ISSUE TITLE
error relating to non-negative integral Numbers and conversion to non-negative integers

### ISSUE THREAD

**Issue by michaelficarra** [es-meta/esmeta#260]
I've not dug too far into this issue. https://github.com/tc39/ecma262/pull/3377 is narrowing the type of [ToLength](https://tc39.es/ecma262/#sec-tolength), an AO used by [LengthOfArrayLike](https://tc39.es/ecma262/#sec-lengthofarraylike), which should be fine. But the esmeta type checker now gives an error on LengthOfArrayLike.

**Comment by jhnaldo** [comment]
It means we no longer have to ignore the type errors related to `LengthOfArrayLike`. Before https://github.com/tc39/ecma262/pull/3377, we have the following error:
```
[ReturnTypeMismatch] return statement in LengthOfArrayLike (step 1, 2:12-59)
- expected: Normal[NonNegInt] | Abrupt[throw]
- actual  : Normal[Int]
```
However, after the PR, the above error is no longer thrown. So, we can safely remove the `LengthOfArrayLike` in the `esmeat-ignore.json` file.

**Comment by michaelficarra** [comment]
Oh, thanks! I didn't understand the error message.
