### ISSUE TITLE
Statistical information of parsed specification

### ISSUE THREAD

**Issue by h2oche** [es-meta/esmeta#29]
- [x] Construct `emu-clause` tree
- [x] Add stat extractor of an algorithm.
    - Ex: counting the # of steps, expressions, and conditions for each kind
    - [x] counting the diverged element
- [x] ~Update parser to record choices (ex: `val parser: P[O] = A | B; O.from == A`)~ (#85)
    - ~Added `Diverged` trait and `DivergedParser` (942f59f24d3f59910d4d0ea9906da5e42214fc5a)~

**Comment by Maokami** [comment]
c318f912a1a9d53b2c22a2a5dad2337be0baa32d

**Comment by h2oche** [comment]
Currently, using `DivergedParser` by extending `EPackratParser` result in buggy behavior since cached result from `EPackratParser` might break the record context in reader data.

For example,
```
lazy val expr: Packrat = p0 ||| p1 ||| p2

lazy val p0: Packrat = "a" ~ expr ~ "0"
lazy val p1: Diverged = "a" ~ expr ~ "1"
lazy val p2: Packrat = id

parse(expr, "a x1") // Error: diverged context of parser p1 is empty since it uses cached input data
```
