### ISSUE TITLE
Import IR Stringifier/Parser/Interp from JISET

### ISSUE THREAD

**Issue by h2oche** [es-meta/esmeta#3]
Import IR Stringifier/Parser/Interp from JISET and remove comments in IR tests.

- [x] Stringify
- [x] Parser
- [x] Interp
- [x] tests

**Comment by jhnaldo** [comment]
14bd8d5399e66a0f906ee4f44e6129f9399f1cfb
ab99ffa9209a449c3a0837f28ca1f29025545348

**Comment by Maokami** [comment]
c4f89986b8612b55787a27b4fb0328311bf7b934
