### ISSUE TITLE
Add tests for IR

### ISSUE THREAD

**Issue by jhnaldo** [es-meta/esmeta#31]
~Fill out more tests for CFGs in https://github.com/es-meta/esmeta/tree/main/tests/cfg.~
Now, IR is introduced and the parser is implemented for IR instead of CFG.
Therefore, this work is deprecated.

**Comment by h2oche** [comment]
`ESubstring`, `EStrConcat`, `EListConcat` added (65590db5a6ddfd4d3cf791bd6fc15c866c8fa14d)
-> Tests added, interp implemented(e770122c1ad52536a91bf5d89cafe78a19880c15)

**Comment by h2oche** [comment]
`ESourceText` added (63ca3d2802878fc701391a06ba390e5c6356b7b4)
