### ISSUE TITLE
Partition Map objects

### ISSUE THREAD

**Issue by h2oche** [es-meta/esmeta#36]
Currently, 
- `MapObj` represents every records & objects (e.g. record object, environment record, ordinary object, function object, ...)
- JS objects have internal `SubMap` property which points to external property map, which is again `MapObj`.
- Environment Record have internal `SubMap` property which points to binding map, which is again `MapObj`.

Desired:
- Partition `MapObj` to `RecordObj`, `JsObj`, `EnvRecObj`, ....
- All objects has a mapping from `String` to `Value`, which represents internal properties.
- `JsObj` has extra mapping for external properties.
- `EnvRecObj` has extra mapping for bindings.
- Partition `EMap` to ... and change compiler.
- Partition `Prop` to ...

Also, consider `FieldLiteral`.

**Comment by jhnaldo** [comment]
In the recent version, we supported records (i.e., `RecordObj`) to represent any values represented as records and maps (i.e., `MapObj`) to illustrate general map data structures used in object properties or bindings in environment records. So, this issue is already resolved.
