### ISSUE TITLE
Add parsing rules for mathematical calculations

### ISSUE THREAD

**Issue by Maokami** [es-meta/esmeta#60]
Currently, an expressions that require mathematical calculations such as cosine, exponentiate are manually handled or not parsed.

In the Spec, they are in the form of "an implementation-approximated Number value representing the result of _calcalation_."

**Comment by Maokami** [comment]
This issue is related to #59.

**Comment by jhnaldo** [comment]
According to the section [4.2 Hosts and Implementations](https://tc39.es/ecma262/#sec-hosts-and-implementations), the meaning of "implementation-defined" and "implementation-approximated" are defined as follows:

> An implementation is an external source that further defines facilities enumerated in Annex D or those that are marked as implementation-defined or implementation-approximated. In informal use, an implementation refers to a concrete artefact, such as a particular web browser.
> - An _implementation-defined_ facility is one that defers its definition to an external source without further qualification. This specification does not make any recommendations for particular behaviours, and conforming implementations are free to choose any behaviour within the constraints put forth by this specification.
> - An _implementation-approximated_ facility is one that defers its definition to an external source while recommending an ideal behaviour. While conforming implementations are free to choose any behaviour within the constraints put forth by this specification, they are encouraged to strive to approximate the ideal. Some mathematical operations, such as Math.exp, are implementation-approximated.

**Comment by jhnaldo** [comment]
Resolved by #91
