### ISSUE TITLE
About completion value

### ISSUE THREAD

**Issue by h2oche** [es-meta/esmeta#65]
Currently, completion value is treated as immutable. However, at the step 7.c.iii.1 of [YieldExpression[2,0].Evaluation](https://tc39.es/ecma262/#prod-YieldExpression), it updates the `[[Value]]` of completion record. I temporarily changed the  `value` field of `Comp` case class to be mutable.

### Related tests
- [language/expressions/async-generator/yield-star-getiter-async-return-method-is-null.js](https://github.com/tc39/test262/blob/main/test/language/expressions/async-generator/yield-star-getiter-async-return-method-is-null.js)
- [language/statements/async-generator/yield-star-return-then-getter-ticks.js](https://github.com/tc39/test262/blob/main/test/language/statements/async-generator/yield-star-return-then-getter-ticks.js)
- [language/statements/async-generator/yield-star-return-missing-value-is-awaited.js](https://github.com/tc39/test262/blob/main/test/language/statements/async-generator/yield-star-return-missing-value-is-awaited.js)

**Comment by jhnaldo** [comment]
I think that completion records are immutable, and this is a strange case to treat completion records as mutable records.

**Comment by jhnaldo** [comment]
We need to open an issue for this problem in the ECMA-262 repository.

**Comment by doehyunbaek** [comment]
Can we close this issue now? @jhnaldo

**Comment by jhnaldo** [comment]
We treat completion values as normal records rather than special structures in https://github.com/es-meta/esmeta/pull/261/commits/78a82db9d6f60eb7347adaad12b1ddc2514af724 and https://github.com/es-meta/esmeta/pull/261/commits/74bbcb923b75c7c4b5f32ed27069d9cce1b7bb3e. So, we can now support mutation for completion records.
