### ISSUE TITLE
[ESMetaError] invalid Lexical access: PrivateIdentifier.StringValue

### ISSUE THREAD

**Issue by F3n67u** [es-meta/esmeta#67]
## How to reproduce 

```bash
$ cat test.js   
class X { constructor(o){ return o } }
class Y extends X { #a }

let o = {}
new Y(o)

$ esmeta js-eval test.js
========================================
 extract phase
----------------------------------------
========================================
 compile phase
----------------------------------------
========================================
 build-cfg phase
----------------------------------------
========================================
 js-eval phase
----------------------------------------
[ESMetaError] invalid Lexical access: PrivateIdentifier.StringValue
```

## Expected
No error

## Actual
throw ESMetaError

**Comment by jhnaldo** [comment]
Hi @F3n67u, thank you for letting us know! We solved this problem and checked that the example program worked well. If you have more questions or inconveniences, please leave issues.

**Comment by F3n67u** [comment]
> Hi @F3n67u, thank you for letting us know! We solved this problem and checked that the example program worked well. If you have more questions or inconveniences, please leave issues.

Thanks for the quick fix. May I suggest fixing our bug via a pull request instead of commit to main branch directly? I want to learn more about how esmeta works from your fix, but I found it is not easier to learn the whole change in several commits.

I am not familiar with scala but I am willing to learn and contribute back. I am very interested in this project.

**Comment by F3n67u** [comment]
I verified this bug is fixed. thanks for your work.

**Comment by jhnaldo** [comment]
> Thanks for the quick fix. May I suggest fixing our bug via a pull request instead of commit to main branch directly? I want to learn more about how esmeta works from your fix, but I found it is not easier to learn the whole change in several commits.
> 
> I am not familiar with scala but I am willing to learn and contribute back. I am very interested in this project.

Hi @F3n67u, I created a pull request (#68) containing all the commits for this bug fix.

**Comment by F3n67u** [comment]
Thanks.
