### ISSUE TITLE
Parse type annotations in spec using lang Parser

### ISSUE THREAD

**Issue by jaehyun1ee** [es-meta/esmeta#81]
Parse type annotations in `spec.html` using `lang/util/Parser.scala`. Try to cover as many cases as possible.

**Comment by jhnaldo** [comment]
The following commits and PRs are related to this issue.

- 377d84c9eab3e9c6bb7547f0b382e5a65a8cdc6d
- 170e1da5db61499795958fe33fe084af108d04e8
- 7ce9e42d017750c693e60bce70074ff33a725bd3
- cc94a2df1d793a9b8ec79fc8cf960f626f2e31f3
- 5c6ba0d02532c6d84917c4a52d1b1e05a71ab6f5
- c45736ecbda71307f3723881ffb534c68b783cd3
- 495cca427f21b8d83c7f14390630d1f5dfa32b06
- 00819671cf513fa85ac495cdecc746024c831b28
- fe1a1d7ca87dbde026f7ac7dd1b675e0f9d2ab76
- afc6a25f117c107468ec58a371a6ded76ffd0766
- 03c7f5aca768017ea4dadad142724bbc560d6878
- 5e4ffcd635c6e4eaf7c5daf5e92fe2216ad8b1c2
- 7ac8799a621cc5ba663a1e6e32ce6a58fe5f2834
- #82

**Comment by jhnaldo** [comment]
According to the `src/main/resources/result/spec-summary` file, the current version has the following success rate for type annotation extraction. We need more advanced type annotation extraction algorithms.
```
- types: 7451 (73.49%)
  - known: 5476
  - unknown: 1975
```

**Comment by jhnaldo** [comment]
We supported all the primary type annotations used in `spec.html`:
```
- types: 6951 (91.53%)
  - known: 6362
  - yet: 589
  - unknown: 613
```
After removing redundant type names, only 124 types remained as edge cases.
I close this issue and treat the remaining cases in separate issues or PRs.
